name: demo_b
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  cupertino_icons: ^0.1.3
  dio: 4.0.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_datetime_picker: 1.5.1
  flutter_icons: 1.1.0
  flutter_local_notifications: ^5.0.0+3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  oktoast: 3.0.0
  package_info: ^0.4.3+4
  provider: 5.0.0
  rxdart: ^0.26.0-nullsafety.1
  shared_preferences: 2.0.6
  syncfusion_flutter_calendar: 19.1.69
  synchronized: 2.2.0
  transparent_image: ^2.0.0
  validators: 3.0.0

dev_dependencies:
  flutter_launcher_icons: 0.7.5
  flutter_launcher_name: 0.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
flutter_launcher_name:
  name: "Phòng họp"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/locales/
    - assets/images/demos/
